# Generated by Django 3.0.9 on 2021-04-18 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.BigIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('empleado', models.CharField(max_length=40)),
                ('tarjeta', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(unique=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=40)),
                ('empleado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('accion', models.CharField(max_length=20)),
                ('trabajo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelos.Trabajos')),
            ],
        ),
    ]
